### ISSUE TITLE
hexdump is horrible. move to openssl

### ISSUE THREAD

**Issue by agardnerIT** [agardnerIT/tracepusher#26]
The documentation currently leverages hexdump to demonstrate the generation of pseudo-random trace and span IDs.

There are a few problems with this approach:

1. hexdump is not universally available (eg. alpine)
2. hexdump syntax is confusing and horrible

By contrast, the `openssl` is ubiquitous and much more easily understood (to me at least).

This issue is to move away from hexdump entirely towards SSL.

Old:
```
trace_id=$(hexdump -vn16 -e'4/4 "%08X" 1 "\n"' /dev/urandom)
span_id=$(hexdump -vn8 -e'4/4 "%08X" 1 "\n"' /dev/urandom)
```

New:

```
trace_id=$(openssl rand -hex 16)
span_id=$(openssl rand -hex 8)
```

**Comment by agardnerIT** [comment]
@medamine-sudo is working on this. If you can drop a comment here, I can assign to you (GitHub is annoying in this regard so sorry about the extra work).

**Comment by MedAmine-SUDO** [comment]
@agardnerIT Done.

**Comment by agardnerIT** [comment]
Fabulous. Merged. Thanks!
