### ISSUE TITLE
Create a static compiled binary as standalone executable for CI/CD download 

### ISSUE THREAD

**Issue by dnsmichi** [agardnerIT/tracepusher#37]
Context: #36 requires dependencies being installed when not using the default CI image.

After researching other CI/CD trace tools, such as [buildevents](https://github.com/honeycombio/buildevents), a static binary to download would decrease the config steps to integrate tracepusher. 

buildevents does not support Otel yet (https://github.com/honeycombio/buildevents/issues/125).

**Comment by agardnerIT** [comment]
I've been experimenting with a few options (cxfreeze and pyinstaller). Both do not compile cross-platform, but I've pushed binaries onto a new branch (built by pyinstaller): https://github.com/agardnerIT/tracepusher/tree/feat/self-contained-binary/dist

For future me, the commands:

```
pip install pyinstaller
pyinstaller --onefile tracepusher.py
cd dist && ls -al
```

Does this fit the bill?

There is also a brand-new Python-superset language called [Mojo](https://github.com/modularml/mojo) which can do both JIT and AOT compilation to produce binaries. It isn't ready yet, but that is something to keep an eye on for the future.

**Comment by dnsmichi** [comment]
@agardnerIT Thanks for your efforts, this is a great first step to reduce dependencies to download and install. I'll run a few tests soon (test MR in https://gitlab.com/gitlab-de/use-cases/observability/devsecops-efficiency/slow-pipeline-for-analysis/-/merge_requests/1)

**Comment by agardnerIT** [comment]
@dnsmichi This is getting stale so I'm going to close it. Please re-open if it is still relevant.
