### ISSUE TITLE
Create requirements.txt for GitHub Actions w/o pytest

### ISSUE THREAD

**Issue by agardnerIT** [agardnerIT/tracepusher#58]
Create a new `requirements-dev.txt` which contains 3 dependencies:

- requests
- PyInstaller
- pytest

# Why?

GitHub actions currently runs `pip install -r requirements.txt` which includes `pytest`.

GitHub actions build binaries workflow doesn't use `pytest` to this is inefficient and pointless.

By having two files, we can have one for the developers (who need `pytest`) and one for everyone else (who probably doesn't).

**Comment by agardnerIT** [comment]
Being done by @viktoriussuwandi  (if you drop a comment here I'll assign this to you)

**Comment by viktoriussuwandi** [comment]
working on it

**Comment by agardnerIT** [comment]
All done in #59 . Thanks!!
