### ISSUE TITLE
Document PyTest, OpenTelemetry and Jaeger integration

### ISSUE THREAD

**Issue by agardnerIT** [agardnerIT/tracepusher#64]
PyTest has an OpenTelemetry plugin to generate traces.

Need to:
1) Add `pytest-opentelemetry==0.6.2` to `requirements.dev`
2) Document in the readme that users can generate traces by running `pytest --export-traces` to a local collector on `http://localhost:4317` (gRPC only)
3) Link to the docs here: https://github.com/chrisguidry/pytest-opentelemetry

**Comment by agardnerIT** [comment]
@viktoriussuwandi GitHub being annoying again. Can you comment so I can assign (just in case someone else comes and starts working on this). Trying to prevent people doing work which isn't merged :) Thanks

**Comment by viktoriussuwandi** [comment]
No problem @agardnerIT
